# Generated by Django 3.1.5 on 2021-01-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='added_by',
        ),
    ]
